site_name: JVol documentation

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - search.highlight

markdown_extensions:
  - mkdocs-typer

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocs-jupyter

nav:
  - index.md
  # - getting-started.md
  - getting-started.ipynb
  - CLI tool: cli-tool.md
  - JpegVolume class: jvol.md
  - encoding.md
  - decoding.md
  - FAQ: faq.md
  - API reference: reference/

# GitHub
copyright: Copyright &copy; 2023 Fernando Pérez García
repo_name: jvol
repo_url: https://github.com/fepegar/jvol
