site_name: JVol documentation

theme:
  name: material
  palette:
    primary: teal
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - navigation.sections
  - search.highlight

plugins:
- search
- mkdocstrings
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocs-jupyter

nav:
- index.md
# - getting-started.md
- getting-started.ipynb
- JpegVolume class: jvol.md
- encoding.md
- decoding.md
- FAQ: faq.md
- API reference: reference/
