site_name: JVol documentation

theme:
  name: material
  palette:
    primary: teal

plugins:
- search
- mkdocstrings
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocs-jupyter

nav:
- index.md
# - getting-started.md
- getting-started.ipynb
- JVol format: jvol.md
- encoding.md
- decoding.md
- FAQ: faq.md
- API reference: reference/
