[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "jvol"
version = "0.1.0"
requires-python = ">=3.8"

dependencies = [
    "einops",
    "scipy",
]

# Define extra dependencies
[project.optional-dependencies]
docs = [
    "mkdocs-material",
]

io = [
    "itk",
    "loguru",
    "typer[all]",
]

tests = [
    "jvol[io]",
    "pytest",
]

dev = [
    "jvol[docs,tests]",
    "black",
    "pre-commit",
    "pyright"
]

[project.scripts]
jvol = "jvol.cli.convert:app"
