[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "jvol"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "einops",
    "humanize",
    "itk",
    "loguru",
    "scipy",
    "transforms3d",
    "typer",
]

[project.optional-dependencies]
docs = [
    "ipywidgets",
    "mkdocs-gen-files",
    "mkdocs-jupyter",
    "mkdocs-literate-nav",
    "mkdocs-material",
    "mkdocs-section-index",
    "mkdocs-typer",
    "mkdocstrings[python]",
]

dev = [
    "jvol[docs]",
    "pre-commit",
    "tox-uv",
]

all = [
    "jvol[dev]",
]

[project.scripts]
jvol = "jvol.cli.convert:app"

[tool.ruff.lint.isort]
force-single-line = true
