name: Docs

on:
  push:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Create and activate virtual environment and
        run: |
          uv venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - uses: actions/cache@v3
        if: github.ref == 'refs/heads/main'
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: uv pip install --system ".[docs]"

      - name: Execute notebooks if on main
        if: github.ref == 'refs/heads/main'
        run: |
          uv pip install --system papermill
          bash scripts/docs/run_notebooks.sh

      - name: Build and deploy to smokeshow
        if: github.ref != 'refs/heads/main'
        run: |
          mkdocs build
          uv pip install --system smokeshow
          smokeshow upload site

      - name: Build and deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
