name: Deploy documentation

on:
  push:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - uses: actions/cache@v3
        if: github.ref == 'refs/heads/main'
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install ".[docs]"

      - name: Execute notebooks
        run: pip install papermill && bash scripts/run_notebooks.sh

      - name: Deploy to smokeshow if branch is not main
        if: github.ref != 'refs/heads/main'
        run: mkdocs build && smokeshow upload site

      - name: Deploy to GitHub Pages if branch is main
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
