name: Deploy documentation

on:
  push:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - uses: actions/cache@v3
        if: github.ref == 'refs/heads/main'
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv pip install --system ".[docs]"

      - name: Execute notebooks if on main
        if: github.ref == 'refs/heads/main'
        run: |
          uv pip install --system papermill
          bash scripts/docs/run_notebooks.sh

      - name: Build and deploy to smokeshow
        if: github.ref != 'refs/heads/main'
        run: |
          mkdocs build
          uv pip install --system smokeshow
          smokeshow upload site

      - name: Build and deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
