name: Docs

on:
  push:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        run: uv python install 3.12

      - name: Create and activate virtual environment and
        run: |
          uv venv
          venv_path=$PWD/.venv
          echo "VIRTUAL_ENV=$venv_path" >> $GITHUB_ENV
          echo "$venv_path/bin" >> $GITHUB_PATH

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - uses: actions/cache@v3
        if: github.ref == 'refs/heads/main'
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: uv pip install ".[docs]"

      - name: Execute notebooks if on main
        run: |
          uv pip install jupyter
          for notebook in $(ls docs/*.ipynb)
          do
              echo $notebook
              jupyter execute --inplace $notebook
          done

      - name: Clean up any large files
        run: |
          find . -name "*.nii*" -type f -delete
          find . -name "*.jvol" -type f -delete
          find . -name "*.zip" -type f -delete

      - name: Build and deploy to smokeshow
        if: github.ref != 'refs/heads/main'
        run: |
          mkdocs build
          uv pip install smokeshow
          smokeshow upload site

      - name: Build and deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
